name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install zip

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: pnpm install
        working-directory: web

      - run: pnpm build
        working-directory: web
        env:
          CI: false

      - run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: bump manifest version to ${{ github.ref_name }}"

      - uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - run: |
          mkdir -p ./temp/peak_minigames
          mkdir -p ./temp/peak_minigames/web
          cp ./{LICENSE,fxmanifest.lua} ./temp/peak_minigames
          cp -r ./client ./temp/peak_minigames
          cp -r ./web/build ./temp/peak_minigames/web/build
          cd ./temp && zip -r ../peak_minigames.zip ./peak_minigames

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ env.RELEASE_VERSION }}
          prerelease: false
          files: peak_minigames.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}